platform:
  - x64
environment:
  matrix:
    - MSYS2_BITS: 64
      MSYSTEM: MINGW64
      ROSWELL_BRANCH: master

install:
  - SET PATH=%USERPROFILE%\.roswell;%PATH%

build_script:
  - C:\msys%MSYS2_BITS%\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER;curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh; exec 0</dev/null;"
  - C:\msys%MSYS2_BITS%\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER;ros install snmsts/sn.github Rudolph-Miller/cl-gists lake; exec 0</dev/null;"

test_script:
  - C:\msys%MSYS2_BITS%\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; lake ; exec 0</dev/null;"
