platform:
  - x64
environment:
  global:
    ROSWELL_BRANCH: release
  matrix:
    - MSYSTEM: MINGW64
      TARGET: x86-64
    - MSYSTEM: MINGW32
      TARGET: x86

install:
  - SET PATH=%USERPROFILE%\.roswell\bin;%PATH%

build_script:
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER;curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh; exec 0</dev/null;"
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER;ros install snmsts/sn.github Rudolph-Miller/cl-gists cl-plus-ssl/cl-plus-ssl lake; exec 0</dev/null;"

test_script:
  - C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; lake.ros ; exec 0</dev/null;"
