platform:
  - x64
environment:
  matrix:
    - MSYS2_BITS: 64
      MSYSTEM: MINGW64
      ROSWELL_BRANCH: master

build_script:
  - C:\msys%MSYS2_BITS%\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER;curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh; exec 0</dev/null;"
  - C:\msys%MSYS2_BITS%\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; if ! which lake ; then ros install snmsts/sn.github Rudolph-Miller/cl-gists lake; fi; exec 0</dev/null;"

test_script:
  - C:\msys%MSYS2_BITS%\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; PATH=$HOME/.roswell/bin:$PATH lake ; exec 0</dev/null;"
