language: c
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - LISP=sbcl-bin/1.4.2

os:
    - linux

matrix:
    include:
      - os: windows
        env:
          - TARGET=x86-64
          - LISP=sbcl-bin/2.0.0
        before_install:
          - choco list -localonly
          - [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
          - choco install --no-progress msys2 --params "/NoUpdate"
          - powershell Install-WindowsFeature Net-Framework-Core
          - choco install wixtoolset
          - RefreshEnv.cmd
          - export msys2="cmd.exe //C C:/tools/msys64/msys2_shell.cmd -defterm -mingw64 -no-start -full-path -here -c \$\* --"
          - $msys2 pacman -S --noconfirm --needed autoconf automake make zlib-devel mingw-w64-x86_64-gcc mingw-w64-i686-gcc
          - export PATH=/c/Users/travis/.roswell/bin:$PATH
          - export WIX="/c/Program Files (x86)/WiX Toolset v3.11"
        before_cache:
          - $msys2 pacman --sync --clean --noconfirm
      - os: linux
        env:
         - TARGET=x86-64,x86
         - MIRROR=t
        addons:
          apt:
            packages:
              - lib32z1-dev
              - gcc-multilib
      - os: osx
        env: TARGET=x86-64,x86
      - os: linux
        arch: arm64
        env: TARGET=arm64
        addons:
          apt:
            packages:
              - libcurl4-openssl-dev
      - os: linux
        service: docker
        env:
          - TARGET=x86-64,x86
          - SUFFIX=-glibc2.10
          - DOCKER=docker.pkg.github.com/roswell/sbcl_bin/glibc2.10-sbcl1.5.7:1
      #- os: linux-ppc64le
      #  env: TARGET=ppc64le LISP=sbcl-bin/1.5.8

      - os: linux
        env: TARGET=x86-64
        stage: deploy
        script: METHOD=upload-build-list ros run -l Lakefile
        after_success:
    exclude:
      - os: linux

cache:
  directories:
    - $HOME/.roswell
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

install:
  - if [ -n "$DOCKER" ]; then
       docker login docker.pkg.github.com -u snmsts -p $GITHUB_OAUTH_TOKEN;
       docker pull $DOCKER;
    fi
  - $msys2 curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - $msys2 ros install snmsts/sn.github

script:
  - if [ -n "$MIRROR" ]; then METHOD=mirror ros run -l Lakefile; fi
  - "if [ -n \"$DOCKER\" ]; then
       docker run \
       -v `pwd`:/tmp \
       -e TARGET=$TARGET \
       -e TRAVIS_BRANCH=$TRAVIS_BRANCH \
       -e TRAVIS_TAG=$TRAVIS_TAG \
       -e VERSION=$VERSION -e SUFFIX=$SUFFIX \
       -it $DOCKER bash \
       -c \"cd /tmp;env METHOD=default ros -l Lakefile\";
    else
      METHOD=default $msys2 ros run -l Lakefile;
    fi"
after_success:
  - METHOD=upload $msys2 ros run -l Lakefile
