language: c
sudo: false

env:
  global:
   - PATH=~/.roswell/bin:$PATH
   - ROSWELL_BRANCH=master
   - ROSWELL_INSTALL_DIR=$HOME/.roswell
   - LISP=sbcl-bin
  matrix:
    - TARGET=x86-64 VERSION=00b6786847b4407214a0dc8d55d12ed8b61bf074 COMMENT=1.3.15
    - TARGET=x86-64 VERSION=0f8f8ae15bc4ace88c3b9e51f21cd93a45376cb4 COMMENT=1.3.16
    - TARGET=x86    VERSION=00b6786847b4407214a0dc8d55d12ed8b61bf074 COMMENT=1.3.15
    - TARGET=x86    VERSION=0f8f8ae15bc4ace88c3b9e51f21cd93a45376cb4 COMMENT=1.3.16

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - lib32z1-dev
      - gcc-multilib

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - if ! which lake ; then ros install snmsts/sn.github Rudolph-Miller/cl-gists lake;lake-tools dump; fi

script:
  - lake
