language: c
sudo: false

env:
  global:
   - PATH=~/.roswell/bin:$PATH
   - ROSWELL_BRANCH=master
   - ROSWELL_INSTALL_DIR=$HOME/.roswell
   - LISP=sbcl-bin

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libc6-i386

cache:
  directories:
    - $HOME/.roswell

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - if ! which lake ; then ros install snmsts/sn.github Rudolph-Miller/cl-gists lake;lake-tools dump; fi

script:
  - if which apt-cache; then apt-cache search lib32gcc; fi
  - lake
