language: c
sudo: false

env:
  global:
   - PATH=~/.roswell/bin:$PATH
   - ROSWELL_BRANCH=master
   - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin

#addons:
#  apt:
#    packages:
#      - libc6-i386

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros install lake snmsts/sn.github snmsts/cl-gists/response-headers

script:
  - lake
