language: c
sudo: false

env:
  global:
   - PATH=~/.roswell/bin:$PATH
   - ROSWELL_BRANCH=master
   - ROSWELL_INSTALL_DIR=$HOME/.roswell
   - LISP=sbcl-bin
   - TASK=mirror
  matrix:
   - VERSION=1.1.18
   - VERSION=1.1.17
   - VERSION=1.1.16
   - VERSION=1.1.15
   - VERSION=1.1.14
   - VERSION=1.1.13
   - VERSION=1.1.12
   - VERSION=1.1.11
   - VERSION=1.1.10
   - VERSION=1.1.9
   - VERSION=1.1.8
   - VERSION=1.1.7
   - VERSION=1.1.6
   - VERSION=1.1.5
   - VERSION=1.1.4
   - VERSION=1.1.3
   - VERSION=1.1.2
   - VERSION=1.1.1
   - VERSION=1.1.0

os:
  - linux
# - osx

matrix:
  exclude:
    - os: osx
      env: LISP=sbcl-bin TASK=mirror

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros install lake snmsts/sn.github Rudolph-Miller/cl-gists

script:
  - lake $TASK
