language: c
sudo: required

env:
  global:
   - PATH=~/.roswell/bin:$PATH
   - ROSWELL_BRANCH=master
   - ROSWELL_INSTALL_DIR=$HOME/.roswell
   - LISP=sbcl-bin/1.4.15

matrix:
  include:
    - os: osx
      env: TARGET=x86-64
    - os: linux
      env: TARGET=x86-64
    - os: osx
      env: TARGET=x86
    - os: linux
      env: TARGET=x86

addons:
  apt:
    packages:
      - lib32z1-dev
      - gcc-multilib

cache:
  directories:
    - $HOME/.roswell

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - if ! which lake ; then ros install snmsts/sn.github Rudolph-Miller/cl-gists lake;lake-tools dump; fi

script:
  - lake

jobs:
  include:
    - stage: deploy
      script: lake upload-buiild-list
      os: linux
