language: c
sudo: false

env:
  global:
   - PATH=~/.roswell/bin:$PATH
   - ROSWELL_BRANCH=master
   - ROSWELL_INSTALL_DIR=$HOME/.roswell
   - LISP=sbcl-bin
   - TASK=mirror
  matrix:
   - VERSION=1.2.16
   - VERSION=1.2.15
   - VERSION=1.2.14
   - VERSION=1.2.13
   - VERSION=1.2.12
   - VERSION=1.2.11
   - VERSION=1.2.10
   - VERSION=1.2.9
   - VERSION=1.2.8
   - VERSION=1.2.7
   - VERSION=1.2.6
   - VERSION=1.2.5
   - VERSION=1.2.4
   - VERSION=1.2.3
   - VERSION=1.2.2
   - VERSION=1.2.1
   - VERSION=1.2.0

os:
  - linux
# - osx

matrix:
  exclude:
    - os: osx
      env: LISP=sbcl-bin TASK=mirror

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros install lake snmsts/sn.github Rudolph-Miller/cl-gists

script:
  - lake $TASK
