language: c
sudo: false

env:
  global:
   - PATH=~/.roswell/bin:$PATH
   - ROSWELL_BRANCH=master
   - ROSWELL_INSTALL_DIR=$HOME/.roswell
   - LISP=sbcl-bin
   - TASK=mirror
  matrix:
   - VERSION=1.3.11
   - VERSION=1.3.9
   - VERSION=1.3.8
   - VERSION=1.3.7
   - VERSION=1.3.6
   - VERSION=1.3.5
   - VERSION=1.3.4
   - VERSION=1.3.3
   - VERSION=1.3.2
   - VERSION=1.3.1
   - VERSION=1.3.0

os:
  - linux
# - osx

matrix:
  exclude:
    - os: osx
      env: LISP=sbcl-bin TASK=mirror

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros install lake snmsts/sn.github Rudolph-Miller/cl-gists

script:
  - lake $TASK
