language: c
sudo: false

env:
  global:
   - PATH=~/.roswell/bin:$PATH
   - ROSWELL_BRANCH=master
   - ROSWELL_INSTALL_DIR=$HOME/.roswell
   - LISP=sbcl-bin
  matrix:
    - VERSION=1.3.10
    - VERSION=1.3.10 UNAME=x86
    - VERSION=1.3.9
    - VERSION=1.3.9 UNAME=x86
    - VERSION=1.3.8
    - VERSION=1.3.8 UNAME=x86
    - VERSION=1.3.7
    - VERSION=1.3.7 UNAME=x86
    - VERSION=1.3.6
    - VERSION=1.3.6 UNAME=x86
    - VERSION=1.3.5
    - VERSION=1.3.5 UNAME=x86
    - VERSION=1.3.4
    - VERSION=1.3.4 UNAME=x86
    - VERSION=1.3.3
    - VERSION=1.3.3 UNAME=x86
    - VERSION=1.3.2
    - VERSION=1.3.2 UNAME=x86
    - VERSION=1.3.1
    - VERSION=1.3.1 UNAME=x86
    - VERSION=1.3.0
    - VERSION=1.3.0 UNAME=x86

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - lib32z1-dev
      - gcc-multilib

cache:
  directories:
    - $HOME/.roswell

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - if ! which lake ; then ros install snmsts/sn.github Rudolph-Miller/cl-gists lake;lake-tools dump; fi

script:
  - lake
