language: c
sudo: required

env:
  global:
   - PATH=~/.roswell/bin:$PATH
   - ROSWELL_BRANCH=master
   - ROSWELL_INSTALL_DIR=$HOME/.roswell
   - LISP=sbcl-bin/1.4.15
  matrix:
   - TARGET=x86-64
   - TARGET=x86

os:
  - osx
  - linux

matrix:
  allow_failures:
    - os: osx
      osx_image: xcode6.4
      env: TARGET=x86-64
    - os: osx
      osx_image: xcode11
      env: TARGET=x86-64

addons:
  apt:
    packages:
      - lib32z1-dev
      - gcc-multilib

cache:
  directories:
    - $HOME/.roswell

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - if ! which lake ; then ros install snmsts/sn.github Rudolph-Miller/cl-gists lake;lake-tools dump; fi

script:
  - lake

jobs:
  include:
    - stage: deploy
      script: lake upload-buiild-list
      os: linux
