language: c
sudo: false

env:
  global:
   - PATH=~/.roswell/bin:$PATH
   - ROSWELL_BRANCH=master
   - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin TASK=mirror

os:
  - osx
  - linux

matrix:
  exclude:
    - os: osx
      env: LISP=sbcl-bin TASK=mirror

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros install lake snmsts/sn.github Rudolph-Miller/cl-gists

script:
  - lake $TASK
