language: c
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - LISP=sbcl-bin/1.4.2
    - mingw64=

os:
    - linux

matrix:
    include:
      - os: windows
        env:
          - PATH=c:\Users\travis\.roswell\bin;$PATH
          - TARGET=x86-64
          - LISP=sbcl-bin/2.0.0
        before_install:
          - [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
          - choco uninstall -y mingw
          - choco upgrade --no-progress -y msys2
          - export msys2='cmd //C RefreshEnv.cmd '
          - export msys2+='& set MSYS=winsymlinks:nativestrict '
          - export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
          - export mingw64="$msys2 -mingw64 -full-path -here -c \$\* --"
          - export msys2+=" -msys2 -c \$\* --"
          - $msys2 pacman --sync --noconfirm --needed autoconf automake make zlib-devel mingw-w64-x86_64-gcc mingw-w64-i686-gcc
          - taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
          - export PATH=/C/tools/msys64/mingw64/bin:/C/Users/travis/.roswell/bin:$PATH
          - export MAKE=mingw32-make
      - os: linux
        env:
         - TARGET=x86-64,x86
         - MIRROR=t
        addons:
          apt:
            packages:
              - lib32z1-dev
              - gcc-multilib
      - os: osx
        env: TARGET=x86-64,x86
      - os: linux
        arch: arm64
        env: TARGET=arm64
        addons:
          apt:
            packages:
              - libcurl4-openssl-dev
      - os: linux
        service: docker
        env:
          - TARGET=x86-64,x86
          - SUFFIX=-glibc2.10
          - DOCKER=docker.pkg.github.com/roswell/sbcl_bin/glibc2.10-sbcl1.5.7:1
      #- os: linux-ppc64le
      #  env: TARGET=ppc64le LISP=sbcl-bin/1.5.8

      - os: linux
        env: TARGET=x86-64
        stage: deploy
        script: METHOD=upload-build-list ros run -l Lakefile
        after_success:
    exclude:
      - os: linux

cache:
  directories:
    - $HOME/.roswell
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64


before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

install:
  - if [ -n "$DOCKER" ]; then
       docker login docker.pkg.github.com -u snmsts -p $GITHUB_OAUTH_TOKEN;
       docker pull $DOCKER;
    fi
  - $mingw64 curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - $mingw64 ros install snmsts/sn.github

script:
  - if [ -n "$MIRROR" ]; then METHOD=mirror ros run -l Lakefile; fi
  - "if [ -n \"$DOCKER\" ]; then
       $mingw64 docker run \
       -v `pwd`:/tmp \
       -e TARGET=$TARGET \
       -e TRAVIS_BRANCH=$TRAVIS_BRANCH \
       -e TRAVIS_TAG=$TRAVIS_TAG \
       -e VERSION=$VERSION -e SUFFIX=$SUFFIX \
       -it $DOCKER bash \
       -c \"cd /tmp;env METHOD=default ros -l Lakefile\";
    else
      METHOD=default $mingw64 ros run -l Lakefile;
    fi"
after_success:
  - METHOD=upload $mingw64 ros run -l Lakefile
