language: c
sudo: false

env:
  global:
   - PATH=~/.roswell/bin:$PATH
   - ROSWELL_BRANCH=master
   - ROSWELL_INSTALL_DIR=$HOME/.roswell
   - LISP=sbcl-bin
   - TASK=mirror
  matrix:
   - VERSION=1.0.58
   - VERSION=1.0.57
   - VERSION=1.0.56
   - VERSION=1.0.55
   - VERSION=1.0.54
   - VERSION=1.0.53
   - VERSION=1.0.52
   - VERSION=1.0.51
   - VERSION=1.0.50
   - VERSION=1.0.49
   - VERSION=1.0.48
   - VERSION=1.0.47
   - VERSION=1.0.46
   - VERSION=1.0.45
   - VERSION=1.0.44
   - VERSION=1.0.43
   - VERSION=1.0.42
   - VERSION=1.0.41
   - VERSION=1.0.40
   - VERSION=1.0.39
   - VERSION=1.0.38
   - VERSION=1.0.37
   - VERSION=1.0.36
   - VERSION=1.0.35
   - VERSION=1.0.34
   - VERSION=1.0.33
   - VERSION=1.0.32
   - VERSION=1.0.31
   - VERSION=1.0.30
   - VERSION=1.0.29
   - VERSION=1.0.28
   - VERSION=1.0.26
   - VERSION=1.0.25
   - VERSION=1.0.24
   - VERSION=1.0.23
   - VERSION=1.0.22
   - VERSION=1.0.21
   - VERSION=1.0.20
   - VERSION=1.0.19
   - VERSION=1.0.18
   - VERSION=1.0.17
   - VERSION=1.0.16
   - VERSION=1.0.15
   - VERSION=1.0.14
   - VERSION=1.0.13
   - VERSION=1.0.12
   - VERSION=1.0.11
   - VERSION=1.0.10
   - VERSION=1.0.9
   - VERSION=1.0.8
   - VERSION=1.0.7
   - VERSION=1.0.6
   - VERSION=1.0.5
   - VERSION=1.0.4
   - VERSION=1.0.3
   - VERSION=1.0.2
   - VERSION=1.0.1
   - VERSION=1.0.0

os:
  - linux
# - osx

matrix:
  exclude:
    - os: osx
      env: LISP=sbcl-bin TASK=mirror

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros install lake snmsts/sn.github Rudolph-Miller/cl-gists

script:
  - lake $TASK
