language: c
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - LISP=sbcl-bin/1.4.2

os:
    - linux
    - osx

matrix:
    allow_failures:
      - os: windows
        env: TARGET=x86-64
    include:
      - os: windows
        env:
          - TARGET=x86-64
          - PATH=/c/tools/msys64/usr/bin:$PATH
        install:
          - choco install --no-progress msys2 --params "/NoUpdate"
          - C:\tools\msys64\usr\bin\bash -c 'pacman -S --noconfirm --needed make'
          - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
          - if ! which lake ; then ros install snmsts/sn.github lake;lake-tools dump; fi
      - os: linux
        arch: arm64
        env: TARGET=arm64
        addons:
          apt:
            packages:
              - libcurl4-openssl-dev
      #- os: linux-ppc64le
      #  env: TARGET=ppc64le LISP=sbcl-bin/1.5.8
      - os: osx
        env: TARGET=x86-64
      - os: linux
        env: TARGET=x86-64
        script: lake mirror; lake
      - os: osx
        env: TARGET=x86
      - os: linux
        env: TARGET=x86
        addons:
          apt:
            packages:
              - lib32z1-dev
              - gcc-multilib
      - os: linux
        env: TARGET=x86-64
        stage: deploy
        script: lake upload-build-list
    exclude:
      - os: linux
      - os: osx

cache:
  directories:
    - $HOME/.roswell

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - if ! which lake ; then ros install snmsts/sn.github lake;lake-tools dump; fi

script:
  - lake; lake upload
