variables:
  ROSWELL_BRANCH: master
  LISP: sbcl-bin/1.4.2

trigger:
- master

jobs:

- job: Linux
  strategy:
    matrix:
      amd64:
        TARGET: "x86-64"
      x86:
        TARGET: "x86"
  variables:
    mingw_path: C:\tools\msys64\usr\bin:/c/Program Files/Steel Bank Common Lisp/1.4.14
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: |
     sudo apt-get -qq -y update
     sudo apt-get -qq -y install libcurl4-openssl-dev lib32z1-dev gcc-multilib
    displayName: 'install required'
  - script: |
     export PATH=~/.roswell/bin:$PATH
     export ROSWELL_INSTALL_DIR=$HOME/.roswell
     curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
    displayName: 'install roswell'

  - script: |
     export PATH=~/.roswell/bin:$PATH
     ros install snmsts/sn.github lake
     lake-tools dump
    displayName: 'setup lake'

  - script: |
     export PATH=~/.roswell/bin:$PATH
     lake
    displayName: 'lake'

- job: macOS
  strategy:
    matrix:
      amd64:
        TARGET: "x86-64"
      x86:
        TARGET: "x86"

  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
     brew install automake autoconf
    displayName: 'install host required'
  - script: |
     export PATH=~/.roswell/bin:$PATH
     export ROSWELL_INSTALL_DIR=$HOME/.roswell
     curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
    displayName: 'install roswell'

  - script: |
     export PATH=~/.roswell/bin:$PATH
     ros install snmsts/sn.github lake
     lake-tools dump
    displayName: 'setup lake'

  - script: |
     export PATH=~/.roswell/bin:$PATH
     lake
    displayName: 'lake'

- job: Windows
  variables:
    mingw_path: C:\tools\msys64\usr\bin
    CC: x86_64-w64-mingw32-gcc

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: |
      choco install --no-progress msys2 --params "/NoUpdate"
    displayName: 'install host msys2'

  - script: |
      C:\tools\msys64\usr\bin\bash -c '/usr/bin/pacman -S --noconfirm --needed mingw-w64-x86_64-gcc make diffutils'
    displayName: 'install gcc'

  - script: |
      C:\tools\msys64\usr\bin\bash -c "PATH=~/.roswell/bin:$PATH ROSWELL_INSTALL_DIR=$HOME/.roswell curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh"
    displayName: 'install roswell'
