variables:
  ROSWELL_BRANCH: master
  ROSWELL_INSTALL_DIR: $HOME/.roswell
  LISP: sbcl-bin/1.4.2

trigger:
- master

jobs:

- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: |
     sudo apt-get -qq -y install libcurl4-openssl-dev
    displayName: 'install required'
  - script: |
     export PATH=~/.roswell/bin:$PATH
     curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
    displayName: 'install roswell'

  - script: |
     ros install snmsts/sn.github lake
     lake-tools dump
    displayName: 'setup lave'
